name: Docker build db image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: eu-central-1

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
 
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::615677714887:role/personal-mehrshad-resume-role
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build, tag, and push docker image to Amazon ECR
      uses: docker/build-push-action@v5
      with:
        context: ./src/db
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: 615677714887.dkr.ecr.eu-central-1.amazonaws.com/ecs-web-application-demo-db-repo
        cache-from: type=gha
        cache-to: type=gha,mode=max
